### ISSUE TITLE
Implement eslint and prettier rules

### ISSUE THREAD

**Issue by soosgyul** [soosgyul/ganz-schon-clever-calculator#2]
The following esLint rules should be used: https://github.com/aerian-studios/eslint-config

Hopefully, anyone who has checked out the project, will be able to format their code in the same way as everyone else, reducing the number of whitespace changes in PR-s.

**Comment by ranjiitk121** [comment]
@gyulasoos I am getting few errors while setting up the eslint and prettier. I would take some more time to learn about both in bit more. I work full time, so sorry for delay.
